import type { CivicIssue } from "../types/index.ts"

/**
 * Client-safe Database Interface & In-Memory Store Provider
 */
export async function getDatabase(): Promise<any> {
  return {
    collection: (name: string) => ({
      find: () => ({ toArray: async () => [...INITIAL_CIVIC_ISSUES] }),
      findOne: async (q: any) => INITIAL_CIVIC_ISSUES.find((i) => i.id === q?.id) || null,
      insertOne: async () => ({ acknowledged: true }),
      insertMany: async () => ({ acknowledged: true }),
      updateOne: async () => ({ acknowledged: true }),
      createIndex: async () => "index_ok",
      countDocuments: async () => INITIAL_CIVIC_ISSUES.length,
    }),
  }
}

export async function getIssuesCollection(): Promise<any> {
  const db = await getDatabase()
  return db.collection("civicIssues")
}

export const INITIAL_CIVIC_ISSUES: CivicIssue[] = [
  // --- CHENNAI, TAMIL NADU ---
  {
    id: "CIV-2026-8X72KQ",
    category: "road",
    title: "Large Pothole on Main Road",
    titleTa: "பிரதான சாலையில் பெரிய குழி",
    description:
      "Deep pothole approximately 60cm wide near the junction. Vehicles are swerving dangerously. Water collects after rain.",
    descriptionTa:
      "சந்திப்பு அருகே சுமார் 60செமீ அகலமுள்ள ஆழமான குழி. வாகனங்கள் ஆபத்தான முறையில் நகர்கின்றன.",
    priority: "high",
    status: "in_progress",
    lat: 13.0382,
    lng: 80.2497,
    accuracy: 8,
    location: { type: "Point", coordinates: [80.2497, 13.0382] },
    address: "Anna Salai, Teynampet, Chennai",
    country: "India",
    state: "Tamil Nadu",
    district: "Chennai",
    localBody: "Greater Chennai Corporation",
    zone: "Zone 10",
    ward: "Ward 142",
    department: "Roads & Infrastructure",
    departmentTa: "சாலைகள் மற்றும் உள்கட்டமைப்பு",
    officer: "Murugan K.",
    slaHours: 72,
    slaRemainingHours: 8,
    slaBreached: false,
    aiConfidence: 94,
    aiSuggestedCategory: "Road Maintenance",
    reportsCount: 7,
    supportersCount: 31,
    upvotes: 31,
    downvotes: 2,
    tags: ["#RoadSafety", "#PotholeAlert", "#ChennaiCorporation", "#UrgentRepair"],
    isFakeImage: false,
    fakeImageReason: "Verified authentic camera snapshot of road infrastructure.",
    comments: [
      {
        id: "c1",
        userName: "Karthik R.",
        text: "This pothole damaged my two-wheeler suspension yesterday.",
        createdAt: "2026-08-09T10:00:00",
      },
      {
        id: "c2",
        userName: "Divya M.",
        text: "Needs urgent asphalt patching before peak monsoon.",
        createdAt: "2026-08-10T11:20:00",
      },
    ],
    anonymous: false,
    submittedAt: "2026-08-08T09:14:00",
    updatedAt: "2026-08-10T14:32:00",
    timeline: [
      {
        status: "submitted",
        label: "Complaint Submitted",
        labelTa: "புகார் பதிவு செய்யப்பட்டது",
        timestamp: "2026-08-08T09:14:00",
        done: true,
        active: false,
      },
      {
        status: "ai_analysis",
        label: "AI Analysis Complete",
        labelTa: "AI பகுப்பாய்வு முடிந்தது",
        timestamp: "2026-08-08T09:15:00",
        note: "Category: Road · Confidence: 94%",
        noteTa: "வகை: சாலை · நம்பகத்தன்மை: 94%",
        done: true,
        active: false,
      },
      {
        status: "assigned",
        label: "Department Assigned",
        labelTa: "துறை ஒதுக்கப்பட்டது",
        timestamp: "2026-08-08T10:00:00",
        note: "Roads & Infrastructure",
        noteTa: "சாலைகள் மற்றும் உள்கட்டமைப்பு",
        done: true,
        active: false,
      },
      {
        status: "accepted",
        label: "Officer Accepted",
        labelTa: "பணியாளர் ஏற்றுக்கொண்டார்",
        timestamp: "2026-08-09T08:00:00",
        note: "Assigned to Murugan K.",
        noteTa: "முருகன் க. க்கு ஒதுக்கப்பட்டது",
        done: true,
        active: false,
      },
      {
        status: "in_progress",
        label: "Work in Progress",
        labelTa: "பணி நடைபெறுகிறது",
        timestamp: "2026-08-10T10:30:00",
        done: true,
        active: true,
      },
      {
        status: "verification",
        label: "Resolution Verification",
        labelTa: "தீர்வு சரிபார்ப்பு",
        timestamp: null,
        done: false,
        active: false,
      },
      {
        status: "resolved",
        label: "Resolved",
        labelTa: "தீர்க்கப்பட்டது",
        timestamp: null,
        done: false,
        active: false,
      },
    ],
  },
  {
    id: "CIV-2026-4A92PL",
    category: "garbage",
    title: "Garbage Overflow Near Market",
    titleTa: "சந்தை அருகே குப்பை நிரம்புதல்",
    description:
      "The garbage bin near T. Nagar market has not been collected for 3 days. Waste is overflowing onto the footpath.",
    descriptionTa:
      "தி நகர் சந்தை அருகிலுள்ள குப்பைத் தொட்டி 3 நாட்களாக எடுக்கப்படவில்லை. கழிவுகள் நடைபாதையில் பரவியுள்ளது.",
    priority: "medium",
    status: "assigned",
    lat: 13.0418,
    lng: 80.234,
    accuracy: 12,
    location: { type: "Point", coordinates: [80.234, 13.0418] },
    address: "Pondy Bazaar, T. Nagar, Chennai",
    country: "India",
    state: "Tamil Nadu",
    district: "Chennai",
    localBody: "Greater Chennai Corporation",
    zone: "Zone 10",
    ward: "Ward 143",
    department: "Sanitation & Solid Waste",
    departmentTa: "சுகாதாரம் மற்றும் திடக்கழிவு",
    officer: null,
    slaHours: 24,
    slaRemainingHours: 6,
    slaBreached: false,
    aiConfidence: 88,
    aiSuggestedCategory: "Garbage Collection",
    reportsCount: 3,
    supportersCount: 14,
    upvotes: 14,
    downvotes: 1,
    tags: ["#CleanChennai", "#GarbageCollection", "#SolidWasteManagement", "#TNagar"],
    isFakeImage: false,
    fakeImageReason: "Verified authentic camera snapshot.",
    comments: [
      {
        id: "c3",
        userName: "Suresh P.",
        text: "The stench is terrible for morning shoppers.",
        createdAt: "2026-08-10T08:30:00",
      },
    ],
    anonymous: true,
    submittedAt: "2026-08-10T07:45:00",
    updatedAt: "2026-08-10T09:00:00",
    timeline: [
      {
        status: "submitted",
        label: "Complaint Submitted",
        labelTa: "புகார் பதிவு செய்யப்பட்டது",
        timestamp: "2026-08-10T07:45:00",
        done: true,
        active: false,
      },
      {
        status: "ai_analysis",
        label: "AI Analysis Complete",
        labelTa: "AI பகுப்பாய்வு முடிந்தது",
        timestamp: "2026-08-10T07:46:00",
        done: true,
        active: false,
      },
      {
        status: "assigned",
        label: "Department Assigned",
        labelTa: "துறை ஒதுக்கப்பட்டது",
        timestamp: "2026-08-10T09:00:00",
        done: true,
        active: true,
      },
      {
        status: "accepted",
        label: "Officer Accepted",
        labelTa: "பணியாளர் ஏற்றுக்கொண்டார்",
        timestamp: null,
        done: false,
        active: false,
      },
      {
        status: "in_progress",
        label: "Work in Progress",
        labelTa: "பணி நடைபெறுகிறது",
        timestamp: null,
        done: false,
        active: false,
      },
      {
        status: "verification",
        label: "Resolution Verification",
        labelTa: "தீர்வு சரிபார்ப்பு",
        timestamp: null,
        done: false,
        active: false,
      },
      {
        status: "resolved",
        label: "Resolved",
        labelTa: "தீர்க்கப்பட்டது",
        timestamp: null,
        done: false,
        active: false,
      },
    ],
  },
  {
    id: "CIV-2026-7M31RT",
    category: "streetlight",
    title: "Street Light Not Working",
    titleTa: "தெரு விளக்கு வேலை செய்யவில்லை",
    description:
      "Three consecutive street lights on the stretch near the school are not functioning. This creates a safety hazard at night.",
    descriptionTa:
      "பள்ளி அருகே தொடர்ச்சியாக மூன்று தெரு விளக்குகள் எரியவில்லை. இரவில் இருட்டாக உள்ளது.",
    priority: "medium",
    status: "resolved",
    lat: 13.0524,
    lng: 80.2287,
    accuracy: 10,
    location: { type: "Point", coordinates: [80.2287, 13.0524] },
    address: "Kodambakkam High Rd, Chennai",
    country: "India",
    state: "Tamil Nadu",
    district: "Chennai",
    localBody: "Greater Chennai Corporation",
    zone: "Zone 10",
    ward: "Ward 142",
    department: "Electrical & Street Lighting",
    departmentTa: "மின்சாரம் & தெரு விளக்கு",
    officer: "Selvam R.",
    slaHours: 48,
    slaRemainingHours: 0,
    slaBreached: false,
    aiConfidence: 91,
    aiSuggestedCategory: "Street Lighting",
    reportsCount: 1,
    supportersCount: 8,
    upvotes: 8,
    downvotes: 0,
    tags: ["#StreetLight", "#NightSafety", "#ChennaiLighting"],
    isFakeImage: false,
    fakeImageReason: "Verified authentic camera snapshot.",
    comments: [],
    anonymous: false,
    submittedAt: "2026-08-05T18:20:00",
    updatedAt: "2026-08-07T16:45:00",
    timeline: [
      {
        status: "submitted",
        label: "Complaint Submitted",
        labelTa: "புகார் பதிவு செய்யப்பட்டது",
        timestamp: "2026-08-05T18:20:00",
        done: true,
        active: false,
      },
      {
        status: "ai_analysis",
        label: "AI Analysis Complete",
        labelTa: "AI பகுப்பாய்வு முடிந்தது",
        timestamp: "2026-08-05T18:21:00",
        done: true,
        active: false,
      },
      {
        status: "assigned",
        label: "Department Assigned",
        labelTa: "துறை ஒதுக்கப்பட்டது",
        timestamp: "2026-08-06T08:00:00",
        done: true,
        active: false,
      },
      {
        status: "accepted",
        label: "Officer Accepted",
        labelTa: "பணியாளர் ஏற்றுக்கொண்டார்",
        timestamp: "2026-08-06T09:00:00",
        done: true,
        active: false,
      },
      {
        status: "in_progress",
        label: "Work in Progress",
        labelTa: "பணி நடைபெறுகிறது",
        timestamp: "2026-08-07T10:00:00",
        done: true,
        active: false,
      },
      {
        status: "verification",
        label: "Resolution Verification",
        labelTa: "தீர்வு சரிபார்ப்பு",
        timestamp: "2026-08-07T15:00:00",
        done: true,
        active: false,
      },
      {
        status: "resolved",
        label: "Resolved",
        labelTa: "தீர்க்கப்பட்டது",
        timestamp: "2026-08-07T16:45:00",
        done: true,
        active: true,
      },
    ],
  },
  {
    id: "CIV-2026-2K58WN",
    category: "water",
    title: "Water Pipe Leakage",
    titleTa: "குழாய் கசிவு",
    description:
      "Underground water pipe is leaking. Potable water is flooding the road and causing traffic issues.",
    descriptionTa:
      "குடிநீர் குழாய் உடைந்து சாலையில் நீர் தேங்கியுள்ளது.",
    priority: "critical",
    status: "in_progress",
    lat: 12.9815,
    lng: 80.218,
    accuracy: 6,
    location: { type: "Point", coordinates: [80.218, 12.9815] },
    address: "Velachery Main Road, Velachery, Chennai",
    country: "India",
    state: "Tamil Nadu",
    district: "Chennai",
    localBody: "Greater Chennai Corporation",
    zone: "Zone 11",
    ward: "Ward 145",
    department: "Water Supply & Sewerage (CMWSSB)",
    departmentTa: "குடிநீர் வழங்கல் மற்றும் கழிவுநீரகற்று வாரியம்",
    officer: "Priya S.",
    slaHours: 24,
    slaRemainingHours: 3,
    slaBreached: false,
    aiConfidence: 93,
    aiSuggestedCategory: "Water Leakage",
    reportsCount: 4,
    supportersCount: 22,
    upvotes: 22,
    downvotes: 0,
    tags: ["#SaveWater", "#WaterLeakage", "#Velachery", "#CMWSSB"],
    isFakeImage: false,
    fakeImageReason: "Verified authentic camera snapshot.",
    comments: [
      {
        id: "c4",
        userName: "Vignesh K.",
        text: "Clean drinking water being wasted for 2 days now.",
        createdAt: "2026-08-11T07:15:00",
      },
    ],
    anonymous: false,
    submittedAt: "2026-08-11T06:00:00",
    updatedAt: "2026-08-11T08:30:00",
    timeline: [
      {
        status: "submitted",
        label: "Complaint Submitted",
        labelTa: "புகார் பதிவு செய்யப்பட்டது",
        timestamp: "2026-08-11T06:00:00",
        done: true,
        active: false,
      },
      {
        status: "ai_analysis",
        label: "AI Analysis Complete",
        labelTa: "AI பகுப்பாய்வு முடிந்தது",
        timestamp: "2026-08-11T06:01:00",
        done: true,
        active: false,
      },
      {
        status: "assigned",
        label: "Department Assigned",
        labelTa: "துறை ஒதுக்கப்பட்டது",
        timestamp: "2026-08-11T07:00:00",
        done: true,
        active: false,
      },
      {
        status: "accepted",
        label: "Officer Accepted",
        labelTa: "பணியாளர் ஏற்றுக்கொண்டார்",
        timestamp: "2026-08-11T07:30:00",
        done: true,
        active: false,
      },
      {
        status: "in_progress",
        label: "Work in Progress",
        labelTa: "பணி நடைபெறுகிறது",
        timestamp: "2026-08-11T08:30:00",
        done: true,
        active: true,
      },
      {
        status: "verification",
        label: "Resolution Verification",
        labelTa: "தீர்வு சரிபார்ப்பு",
        timestamp: null,
        done: false,
        active: false,
      },
      {
        status: "resolved",
        label: "Resolved",
        labelTa: "தீர்க்கப்பட்டது",
        timestamp: null,
        done: false,
        active: false,
      },
    ],
  },
  // --- VELLORE, TAMIL NADU ---
  {
    id: "CIV-2026-9V41KP",
    category: "road",
    title: "Severe Road Surface Erosion near Katpadi Bus Stop",
    titleTa: "காட்பாடி பேருந்து நிறுத்தம் அருகே தார் சாலை சேதம்",
    description:
      "Heavy road erosion with deep craters causing major traffic jams during peak college hours near Katpadi junction.",
    descriptionTa:
      "காட்பாடி சந்திப்பு அருகே தார் சாலை பெயர்ந்து பள்ளங்கள் உருவாகியுள்ளன.",
    priority: "high",
    status: "submitted",
    lat: 12.9698,
    lng: 79.1378,
    accuracy: 14,
    location: { type: "Point", coordinates: [79.1378, 12.9698] },
    address: "Katpadi Main Road, Katpadi, Vellore",
    country: "India",
    state: "Tamil Nadu",
    district: "Vellore",
    localBody: "Vellore City Municipal Corporation",
    zone: "Zone 2",
    ward: "Ward 12",
    department: "Municipal Road Maintenance",
    departmentTa: "நகராட்சி சாலை பராமரிப்பு",
    officer: null,
    slaHours: 48,
    slaRemainingHours: 46,
    slaBreached: false,
    aiConfidence: 95,
    aiSuggestedCategory: "Road Maintenance",
    reportsCount: 5,
    supportersCount: 19,
    upvotes: 19,
    downvotes: 1,
    tags: ["#Katpadi", "#VelloreCorporation", "#RoadDamage", "#StudentSafety"],
    isFakeImage: false,
    fakeImageReason: "Verified authentic camera snapshot.",
    comments: [],
    anonymous: false,
    submittedAt: "2026-08-11T14:10:00",
    updatedAt: "2026-08-11T14:12:00",
    timeline: [
      {
        status: "submitted",
        label: "Complaint Submitted",
        labelTa: "புகார் பதிவு செய்யப்பட்டது",
        timestamp: "2026-08-11T14:10:00",
        done: true,
        active: false,
      },
      {
        status: "ai_analysis",
        label: "AI Analysis Complete",
        labelTa: "AI பகுப்பாய்வு முடிந்தது",
        timestamp: "2026-08-11T14:12:00",
        done: true,
        active: true,
      },
      {
        status: "assigned",
        label: "Department Assigned",
        labelTa: "துறை ஒதுக்கப்பட்டது",
        timestamp: null,
        done: false,
        active: false,
      },
      {
        status: "accepted",
        label: "Officer Accepted",
        labelTa: "பணியாளர் ஏற்றுக்கொண்டார்",
        timestamp: null,
        done: false,
        active: false,
      },
      {
        status: "in_progress",
        label: "Work in Progress",
        labelTa: "பணி நடைபெறுகிறது",
        timestamp: null,
        done: false,
        active: false,
      },
      {
        status: "verification",
        label: "Resolution Verification",
        labelTa: "தீர்வு சரிபார்ப்பு",
        timestamp: null,
        done: false,
        active: false,
      },
      {
        status: "resolved",
        label: "Resolved",
        labelTa: "தீர்க்கப்பட்டது",
        timestamp: null,
        done: false,
        active: false,
      },
    ],
  },
  // --- COIMBATORE, TAMIL NADU ---
  {
    id: "CIV-2026-3C77RT",
    category: "drainage",
    title: "Clogged Stormwater Drain Overflowing onto Avinashi Road",
    titleTa: "அவினாசி சாலையில் மழைநீர் வடிகால் அடைப்பு",
    description:
      "Drainage channel blocked by plastic bottles and construction debris. Stagnant foul water spilling onto pedestrian pavement.",
    descriptionTa:
      "அவினாசி சாலையில் மழைநீர் வடிகால் அடைத்து தண்ணீர் தேங்கியுள்ளது.",
    priority: "high",
    status: "in_progress",
    lat: 11.0168,
    lng: 76.9558,
    accuracy: 9,
    location: { type: "Point", coordinates: [76.9558, 11.0168] },
    address: "Avinashi Road, Peelamedu, Coimbatore",
    country: "India",
    state: "Tamil Nadu",
    district: "Coimbatore",
    localBody: "Coimbatore City Municipal Corporation",
    zone: "East Zone",
    ward: "Ward 55",
    department: "Drainage & Sewerage",
    departmentTa: "வடிகால் & கழிவுநீரகற்று",
    officer: "Kishore Kumar",
    slaHours: 48,
    slaRemainingHours: 12,
    slaBreached: false,
    aiConfidence: 92,
    aiSuggestedCategory: "Drainage Block",
    reportsCount: 6,
    supportersCount: 28,
    upvotes: 28,
    downvotes: 0,
    tags: ["#Coimbatore", "#DrainageBlock", "#Peelamedu", "#AvinashiRoad"],
    isFakeImage: false,
    fakeImageReason: "Verified authentic camera snapshot.",
    comments: [],
    anonymous: false,
    submittedAt: "2026-08-09T16:00:00",
    updatedAt: "2026-08-10T12:00:00",
    timeline: [
      {
        status: "submitted",
        label: "Complaint Submitted",
        labelTa: "புகார் பதிவு செய்யப்பட்டது",
        timestamp: "2026-08-09T16:00:00",
        done: true,
        active: false,
      },
      {
        status: "ai_analysis",
        label: "AI Analysis Complete",
        labelTa: "AI பகுப்பாய்வு முடிந்தது",
        timestamp: "2026-08-09T16:01:00",
        done: true,
        active: false,
      },
      {
        status: "assigned",
        label: "Department Assigned",
        labelTa: "துறை ஒதுக்கப்பட்டது",
        timestamp: "2026-08-09T18:00:00",
        done: true,
        active: false,
      },
      {
        status: "accepted",
        label: "Officer Accepted",
        labelTa: "பணியாளர் ஏற்றுக்கொண்டார்",
        timestamp: "2026-08-10T08:00:00",
        done: true,
        active: false,
      },
      {
        status: "in_progress",
        label: "Work in Progress",
        labelTa: "பணி நடைபெறுகிறது",
        timestamp: "2026-08-10T12:00:00",
        done: true,
        active: true,
      },
      {
        status: "verification",
        label: "Resolution Verification",
        labelTa: "தீர்வு சரிபார்ப்பு",
        timestamp: null,
        done: false,
        active: false,
      },
      {
        status: "resolved",
        label: "Resolved",
        labelTa: "தீர்க்கப்பட்டது",
        timestamp: null,
        done: false,
        active: false,
      },
    ],
  },
  // --- BENGALURU, KARNATAKA ---
  {
    id: "CIV-2026-5B12NK",
    category: "traffic",
    title: "Broken Traffic Signal on Outer Ring Road",
    titleTa: "வெளிவட்டச் சாலையில் பழுதடைந்த போக்குவரத்து சிக்னல்",
    description:
      "Signal lights in blinking error mode causing severe gridlock at Marathahalli junction.",
    descriptionTa:
      "மராத்தஹள்ளி சந்திப்பில் சிக்னல் பழுதால் போக்குவரத்து நெரிசல் ஏற்பட்டுள்ளது.",
    priority: "critical",
    status: "assigned",
    lat: 12.9569,
    lng: 77.7011,
    accuracy: 11,
    location: { type: "Point", coordinates: [77.7011, 12.9569] },
    address: "Outer Ring Road, Marathahalli, Bengaluru",
    country: "India",
    state: "Karnataka",
    district: "Bengaluru Urban",
    localBody: "Bruhat Bengaluru Mahanagara Palike (BBMP)",
    zone: "Mahadevapura",
    ward: "Ward 85",
    department: "Traffic Police & Urban Safety",
    departmentTa: "போக்குவரத்து காவல்துறை",
    officer: null,
    slaHours: 12,
    slaRemainingHours: 4,
    slaBreached: false,
    aiConfidence: 96,
    aiSuggestedCategory: "Traffic Signal",
    reportsCount: 9,
    supportersCount: 45,
    upvotes: 45,
    downvotes: 2,
    tags: ["#BengaluruTraffic", "#Marathahalli", "#TrafficSignal", "#ORR"],
    isFakeImage: false,
    fakeImageReason: "Verified authentic camera snapshot.",
    comments: [],
    anonymous: false,
    submittedAt: "2026-08-11T12:00:00",
    updatedAt: "2026-08-11T13:00:00",
    timeline: [
      {
        status: "submitted",
        label: "Complaint Submitted",
        labelTa: "புகார் பதிவு செய்யப்பட்டது",
        timestamp: "2026-08-11T12:00:00",
        done: true,
        active: false,
      },
      {
        status: "ai_analysis",
        label: "AI Analysis Complete",
        labelTa: "AI பகுப்பாய்வு முடிந்தது",
        timestamp: "2026-08-11T12:01:00",
        done: true,
        active: false,
      },
      {
        status: "assigned",
        label: "Department Assigned",
        labelTa: "துறை ஒதுக்கப்பட்டது",
        timestamp: "2026-08-11T13:00:00",
        done: true,
        active: true,
      },
      {
        status: "accepted",
        label: "Officer Accepted",
        labelTa: "பணியாளர் ஏற்றுக்கொண்டார்",
        timestamp: null,
        done: false,
        active: false,
      },
      {
        status: "in_progress",
        label: "Work in Progress",
        labelTa: "பணி நடைபெறுகிறது",
        timestamp: null,
        done: false,
        active: false,
      },
      {
        status: "verification",
        label: "Resolution Verification",
        labelTa: "தீர்வு சரிபார்ப்பு",
        timestamp: null,
        done: false,
        active: false,
      },
      {
        status: "resolved",
        label: "Resolved",
        labelTa: "தீர்க்கப்பட்டது",
        timestamp: null,
        done: false,
        active: false,
      },
    ],
  },
]
