import mongoose from "mongoose"
import dotenv from "dotenv"
import { connectMongoDB } from "./config/db.js"
import { CivicIssueModel } from "./models/CivicIssue.js"

dotenv.config()

export function makeBeforeSvg(title: string, cat: string, color: string, icon: string): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400" viewBox="0 0 600 400"><rect width="600" height="400" fill="#f8fafc"/><rect x="20" y="20" width="560" height="360" rx="16" fill="#f1f5f9" stroke="${color}" stroke-width="3"/><circle cx="300" cy="150" r="48" fill="${color}" fill-opacity="0.2"/><text x="300" y="162" font-size="44" text-anchor="middle" font-family="system-ui, sans-serif">${icon}</text><rect x="20" y="20" width="110" height="32" rx="8" fill="#dc2626"/><text x="75" y="41" font-size="12" font-weight="900" fill="#ffffff" text-anchor="middle" font-family="system-ui, sans-serif">BEFORE</text><text x="300" y="240" font-size="18" font-weight="bold" fill="#0f172a" text-anchor="middle" font-family="system-ui, sans-serif">${title}</text><text x="300" y="270" font-size="13" font-weight="600" fill="${color}" text-anchor="middle" font-family="system-ui, sans-serif">Reported Incident Evidence</text><text x="300" y="340" font-size="11" fill="#64748b" text-anchor="middle" font-family="system-ui, sans-serif">📷 Citizen Geo-Tagged Photo</text></svg>`
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`
}

export function makeAfterSvg(title: string, officer: string): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400" viewBox="0 0 600 400"><rect width="600" height="400" fill="#f0fdf4"/><rect x="20" y="20" width="560" height="360" rx="16" fill="#dc2626" fill-opacity="0.05" stroke="#16a34a" stroke-width="4"/><circle cx="300" cy="150" r="48" fill="#16a34a" fill-opacity="0.2"/><text x="300" y="165" font-size="48" text-anchor="middle" font-family="system-ui, sans-serif">✓</text><rect x="20" y="20" width="120" height="32" rx="8" fill="#16a34a"/><text x="80" y="41" font-size="12" font-weight="900" fill="#ffffff" text-anchor="middle" font-family="system-ui, sans-serif">AFTER ✓</text><text x="300" y="230" font-size="18" font-weight="bold" fill="#14532d" text-anchor="middle" font-family="system-ui, sans-serif">Repair Completed</text><text x="300" y="260" font-size="13" font-weight="600" fill="#15803d" text-anchor="middle" font-family="system-ui, sans-serif">${title}</text><rect x="150" y="295" width="300" height="36" rx="8" fill="#dcfce7" stroke="#86efac"/><text x="300" y="318" font-size="12" font-weight="700" fill="#166534" text-anchor="middle" font-family="system-ui, sans-serif">Verified by ${officer}</text></svg>`
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`
}

export const SEED_ISSUES = [
  {
    id: "CIV-2026-8X72KQ",
    category: "road",
    title: "Large Pothole on Main Road",
    titleTa: "பிரதான சாலையில் பெரிய குழி",
    description:
      "Deep pothole approximately 60cm wide near the junction. Vehicles are swerving dangerously. Water collects after rain.",
    descriptionTa:
      "சந்திப்பு அருகே சுமார் 60செமீ அகலமுள்ள ஆழமான குழி. வாகனங்கள் ஆபத்தான முறையில் நகர்கின்றன.",
    priority: "high",
    status: "resolved",
    lat: 13.0382,
    lng: 80.2497,
    accuracy: 8,
    location: { type: "Point", coordinates: [80.2497, 13.0382] },
    address: "Anna Salai, Teynampet, Chennai",
    country: "India",
    state: "Tamil Nadu",
    district: "Chennai",
    localBody: "Greater Chennai Corporation",
    zone: "Zone 10",
    ward: "Ward 142",
    department: "Roads & Infrastructure",
    departmentTa: "சாலைகள் மற்றும் உள்கட்டமைப்பு",
    officer: "Murugan K.",
    slaHours: 72,
    slaRemainingHours: 0,
    slaBreached: false,
    aiConfidence: 94,
    aiSuggestedCategory: "Road Maintenance",
    reportsCount: 7,
    supportersCount: 31,
    upvotes: 31,
    downvotes: 2,
    imageUrl: makeBeforeSvg("Large Pothole on Main Road", "road", "#dc2626", "🛣️"),
    resolvedImageUrl: makeAfterSvg("Large Pothole on Main Road", "Officer Murugan K."),
    resolvedAt: "2026-08-11T14:32:00",
    resolutionNotes: "Asphalt patch completed, road resurfaced, and safety inspected.",
    comments: [
      {
        id: "c1",
        userName: "Karthik R.",
        text: "This pothole damaged my two-wheeler suspension yesterday.",
        createdAt: "2026-08-09T10:00:00",
      },
      {
        id: "c2",
        userName: "Divya M.",
        text: "Needs urgent asphalt patching before peak monsoon.",
        createdAt: "2026-08-10T11:20:00",
      },
    ],
    anonymous: false,
    citizenName: "Karthikeyan M.",
    citizenPhone: "9840123456",
    submittedAt: "2026-08-08T09:14:00",
    updatedAt: "2026-08-11T14:32:00",
    timeline: [
      {
        status: "submitted",
        label: "Complaint Submitted",
        labelTa: "புகார் பதிவு செய்யப்பட்டது",
        timestamp: "2026-08-08T09:14:00",
        done: true,
        active: false,
      },
      {
        status: "ai_analysis",
        label: "AI Analysis Complete",
        labelTa: "AI பகுப்பாய்வு முடிந்தது",
        timestamp: "2026-08-08T09:15:00",
        note: "Category: Road · Confidence: 94%",
        noteTa: "வகை: சாலை · நம்பகத்தன்மை: 94%",
        done: true,
        active: false,
      },
      {
        status: "assigned",
        label: "Department Assigned",
        labelTa: "துறை ஒதுக்கப்பட்டது",
        timestamp: "2026-08-08T10:00:00",
        note: "Roads & Infrastructure",
        noteTa: "சாலைகள் மற்றும் உள்கட்டமைப்பு",
        done: true,
        active: false,
      },
      {
        status: "accepted",
        label: "Officer Accepted",
        labelTa: "பணியாளர் ஏற்றுக்கொண்டார்",
        timestamp: "2026-08-09T08:00:00",
        note: "Assigned to Murugan K.",
        noteTa: "முருகன் க. க்கு ஒதுக்கப்பட்டது",
        done: true,
        active: false,
      },
      {
        status: "in_progress",
        label: "Work in Progress",
        labelTa: "பணி நடைபெறுகிறது",
        timestamp: "2026-08-10T10:30:00",
        done: true,
        active: false,
      },
      {
        status: "resolved",
        label: "Resolved",
        labelTa: "தீர்க்கப்பட்டது",
        timestamp: "2026-08-11T14:32:00",
        done: true,
        active: true,
      },
    ],
  },
  {
    id: "CIV-2026-9P43LM",
    category: "garbage",
    title: "Overflowing Garbage Dump near Market",
    titleTa: "சந்தை அருகே நிரம்பி வழியும் குப்பைக் குவியல்",
    description:
      "The garbage bin near T. Nagar market has not been collected for 3 days. Waste is overflowing onto the footpath.",
    descriptionTa:
      "தி நகர் சந்தை அருகிலுள்ள குப்பைத் தொட்டி 3 நாட்களாக எடுக்கப்படவில்லை. கழிவுகள் நடைபாதையில் பரவியுள்ளது.",
    priority: "medium",
    status: "resolved",
    lat: 13.0418,
    lng: 80.234,
    accuracy: 12,
    location: { type: "Point", coordinates: [80.234, 13.0418] },
    address: "Pondy Bazaar, T. Nagar, Chennai",
    country: "India",
    state: "Tamil Nadu",
    district: "Chennai",
    localBody: "Greater Chennai Corporation",
    zone: "Zone 10",
    ward: "Ward 143",
    department: "Sanitation & Solid Waste",
    departmentTa: "சுகாதாரம் மற்றும் திடக்கழிவு",
    officer: "Selvam P.",
    slaHours: 24,
    slaRemainingHours: 0,
    slaBreached: false,
    aiConfidence: 91,
    aiSuggestedCategory: "Garbage Removal",
    reportsCount: 4,
    supportersCount: 19,
    upvotes: 19,
    downvotes: 1,
    imageUrl: makeBeforeSvg("Overflowing Garbage Dump near Market", "garbage", "#d97706", "🗑️"),
    resolvedImageUrl: makeAfterSvg("Overflowing Garbage Dump near Market", "Officer Selvam P."),
    resolvedAt: "2026-08-11T16:00:00",
    resolutionNotes: "Garbage cleared, bin disinfected, and area sanitized.",
    comments: [],
    anonymous: true,
    submittedAt: "2026-08-11T06:00:00",
    updatedAt: "2026-08-11T16:00:00",
    timeline: [
      {
        status: "submitted",
        label: "Complaint Submitted",
        labelTa: "புகார் பதிவு செய்யப்பட்டது",
        timestamp: "2026-08-11T06:00:00",
        done: true,
        active: false,
      },
      {
        status: "ai_analysis",
        label: "AI Analysis Complete",
        labelTa: "AI பகுப்பாய்வு முடிந்தது",
        timestamp: "2026-08-11T06:01:00",
        done: true,
        active: false,
      },
      {
        status: "resolved",
        label: "Resolved",
        labelTa: "தீர்க்கப்பட்டது",
        timestamp: "2026-08-11T16:00:00",
        done: true,
        active: true,
      },
    ],
  },
  {
    id: "CIV-2026-2K81QW",
    category: "streetlight",
    title: "Broken Streetlight on 4th Main Road",
    titleTa: "4வது பிரதான சாலையில் உடைந்த தெருவிளக்கு",
    description:
      "Streetlight fixture broken and hanging dangerously. Dark stretch creating safety concerns at night.",
    descriptionTa:
      "தெருவிளக்கு உடைந்த நிலையில் தொங்குகிறது. இரவு நேரத்தில் இருளாக இருப்பதால் பாதுகாப்பு குறைபாடு.",
    priority: "high",
    status: "in_progress",
    lat: 13.0827,
    lng: 80.2707,
    accuracy: 6,
    location: { type: "Point", coordinates: [80.2707, 13.0827] },
    address: "4th Main Road, Anna Nagar, Chennai",
    country: "India",
    state: "Tamil Nadu",
    district: "Chennai",
    localBody: "Greater Chennai Corporation",
    zone: "Zone 8",
    ward: "Ward 102",
    department: "Electrical & Lighting",
    departmentTa: "மின்சாரம் மற்றும் விளக்குகள்",
    officer: "Ramesh K.",
    slaHours: 48,
    slaRemainingHours: 36,
    slaBreached: false,
    aiConfidence: 88,
    aiSuggestedCategory: "Street Light Maintenance",
    reportsCount: 2,
    supportersCount: 14,
    upvotes: 14,
    downvotes: 0,
    imageUrl: makeBeforeSvg("Broken Streetlight on 4th Main Road", "streetlight", "#ca8a04", "💡"),
    resolvedImageUrl: makeAfterSvg("Broken Streetlight on 4th Main Road", "Officer Ramesh K."),
    comments: [],
    anonymous: true,
    submittedAt: "2026-08-12T08:30:00",
    updatedAt: "2026-08-12T08:30:00",
    timeline: [
      {
        status: "submitted",
        label: "Complaint Submitted",
        labelTa: "புகார் பதிவு செய்யப்பட்டது",
        timestamp: "2026-08-12T08:30:00",
        done: true,
        active: true,
      },
    ],
  },
  {
    id: "CIV-2026-5T99ZZ",
    category: "water",
    title: "Drinking Water Pipe Leakage",
    titleTa: "குடிநீர் குழாய் கசிவு",
    description:
      "Main supply pipe leaking heavily near Metro station entrance. Clean drinking water wasting onto the road.",
    descriptionTa:
      "மெட்ரோ ரயில் நிலைய நுழைவாயில் அருகே குடிநீர் குழாயில் பெருமளவில் நீர் கசிகிறது.",
    priority: "critical",
    status: "resolved",
    lat: 13.0604,
    lng: 80.2496,
    accuracy: 5,
    location: { type: "Point", coordinates: [80.2496, 13.0604] },
    address: "Near Metro Gate B, Thousand Lights, Chennai",
    country: "India",
    state: "Tamil Nadu",
    district: "Chennai",
    localBody: "Chennai Metro Water Supply",
    zone: "Zone 9",
    ward: "Ward 118",
    department: "Water Supply & Sewerage",
    departmentTa: "குடிநீர் மற்றும் கழிவுநீர்",
    officer: "Srinivasan P.",
    slaHours: 24,
    slaRemainingHours: 0,
    slaBreached: false,
    aiConfidence: 96,
    aiSuggestedCategory: "Water Leakage",
    reportsCount: 12,
    supportersCount: 52,
    upvotes: 52,
    downvotes: 0,
    imageUrl: makeBeforeSvg("Drinking Water Pipe Leakage", "water", "#2563eb", "💧"),
    resolvedImageUrl: makeAfterSvg("Drinking Water Pipe Leakage", "Officer Srinivasan P."),
    resolvedAt: "2026-08-07T15:30:00",
    resolutionNotes: "Main supply pipeline joint welded, sealed, and pressure tested.",
    comments: [
      {
        id: "c3",
        userName: "Vasanth H.",
        text: "Fixed quickly by CMWSSB team within 18 hours! Excellent response.",
        createdAt: "2026-08-07T16:00:00",
      },
    ],
    anonymous: false,
    citizenName: "Vasanth H.",
    citizenPhone: "9876543210",
    submittedAt: "2026-08-06T10:00:00",
    updatedAt: "2026-08-07T15:30:00",
    timeline: [
      {
        status: "submitted",
        label: "Complaint Submitted",
        labelTa: "புகார் பதிவு செய்யப்பட்டது",
        timestamp: "2026-08-06T10:00:00",
        done: true,
        active: false,
      },
      {
        status: "ai_analysis",
        label: "AI Analysis Complete",
        labelTa: "AI பகுப்பாய்வு முடிந்தது",
        timestamp: "2026-08-06T10:02:00",
        done: true,
        active: false,
      },
      {
        status: "resolved",
        label: "Resolved",
        labelTa: "தீர்க்கப்பட்டது",
        timestamp: "2026-08-07T15:30:00",
        done: true,
        active: true,
      },
    ],
  },
  {
    id: "CIV-2026-3C77RT",
    category: "drainage",
    title: "Clogged Stormwater Drain Overflowing onto Avinashi Road",
    titleTa: "அவினாசி சாலையில் மழைநீர் வடிகால் அடைப்பு",
    description:
      "Drainage channel blocked by plastic bottles and construction debris. Stagnant foul water spilling onto pedestrian pavement.",
    descriptionTa:
      "அவினாசி சாலையில் மழைநீர் வடிகால் அடைத்து தண்ணீர் தேங்கியுள்ளது.",
    priority: "high",
    status: "in_progress",
    lat: 11.0168,
    lng: 76.9558,
    accuracy: 9,
    location: { type: "Point", coordinates: [76.9558, 11.0168] },
    address: "Avinashi Road, Peelamedu, Coimbatore",
    country: "India",
    state: "Tamil Nadu",
    district: "Coimbatore",
    localBody: "Coimbatore City Municipal Corporation",
    zone: "East Zone",
    ward: "Ward 55",
    department: "Drainage & Sewerage",
    departmentTa: "வடிகால் & கழிவுநீரகற்று",
    officer: "Kishore Kumar",
    slaHours: 48,
    slaRemainingHours: 12,
    slaBreached: false,
    aiConfidence: 92,
    aiSuggestedCategory: "Drainage Block",
    reportsCount: 6,
    supportersCount: 28,
    upvotes: 28,
    downvotes: 0,
    imageUrl: makeBeforeSvg("Clogged Stormwater Drain Overflowing", "drainage", "#7c3aed", "🚰"),
    resolvedImageUrl: makeAfterSvg("Clogged Stormwater Drain Overflowing", "Officer Kishore Kumar"),
    comments: [],
    anonymous: false,
    submittedAt: "2026-08-09T16:00:00",
    updatedAt: "2026-08-10T12:00:00",
    timeline: [
      {
        status: "submitted",
        label: "Complaint Submitted",
        labelTa: "புகார் பதிவு செய்யப்பட்டது",
        timestamp: "2026-08-09T16:00:00",
        done: true,
        active: false,
      },
      {
        status: "in_progress",
        label: "Work in Progress",
        labelTa: "பணி நடைபெறுகிறது",
        timestamp: "2026-08-10T12:00:00",
        done: true,
        active: true,
      },
    ],
  },
  {
    id: "CIV-2026-5B12NK",
    category: "traffic",
    title: "Broken Traffic Signal on Outer Ring Road",
    titleTa: "வெளிவட்டச் சாலையில் பழுதடைந்த போக்குவரத்து சிக்னல்",
    description:
      "Signal lights in blinking error mode causing severe gridlock at Marathahalli junction.",
    descriptionTa:
      "மராத்தஹள்ளி சந்திப்பில் சிக்னல் பழுதால் போக்குவரத்து நெரிசல் ஏற்பட்டுள்ளது.",
    priority: "critical",
    status: "assigned",
    lat: 12.9569,
    lng: 77.7011,
    accuracy: 11,
    location: { type: "Point", coordinates: [77.7011, 12.9569] },
    address: "Outer Ring Road, Marathahalli, Bengaluru",
    country: "India",
    state: "Karnataka",
    district: "Bengaluru Urban",
    localBody: "Bruhat Bengaluru Mahanagara Palike (BBMP)",
    zone: "Mahadevapura",
    ward: "Ward 85",
    department: "Traffic Police & Urban Safety",
    departmentTa: "போக்குவரத்து காவல்துறை",
    officer: null,
    slaHours: 12,
    slaRemainingHours: 4,
    slaBreached: false,
    aiConfidence: 96,
    aiSuggestedCategory: "Traffic Signal",
    reportsCount: 9,
    supportersCount: 45,
    upvotes: 45,
    downvotes: 2,
    imageUrl: makeBeforeSvg("Broken Traffic Signal on Outer Ring Road", "traffic", "#dc2626", "🚦"),
    resolvedImageUrl: makeAfterSvg("Broken Traffic Signal on Outer Ring Road", "Traffic Control Unit"),
    comments: [],
    anonymous: false,
    submittedAt: "2026-08-11T12:00:00",
    updatedAt: "2026-08-11T13:00:00",
    timeline: [
      {
        status: "submitted",
        label: "Complaint Submitted",
        labelTa: "புகார் பதிவு செய்யப்பட்டது",
        timestamp: "2026-08-11T12:00:00",
        done: true,
        active: false,
      },
      {
        status: "assigned",
        label: "Department Assigned",
        labelTa: "துறை ஒதுக்கப்பட்டது",
        timestamp: "2026-08-11T13:00:00",
        done: true,
        active: true,
      },
    ],
  },
]

export async function seedDatabase(exitOnComplete: boolean = false) {
  try {
    console.log("🌱 Seeding initial civic issues with Before & After photos to MongoDB...")

    for (const issue of SEED_ISSUES) {
      await CivicIssueModel.updateOne(
        { id: issue.id },
        { $set: issue },
        { upsert: true }
      )
      console.log(`  ✓ Seeded: ${issue.id} - ${issue.title} (Status: ${issue.status})`)
    }

    console.log("🎉 Database seeding completed successfully!")
    if (exitOnComplete) process.exit(0)
  } catch (error) {
    console.error("❌ Seeding failed:", error)
    if (exitOnComplete) process.exit(1)
  }
}

if (process.argv[1] && process.argv[1].endsWith("seed.ts")) {
  connectMongoDB().then(() => seedDatabase(true))
}

